export { bindEscape, type EscapeOptions } from './escape.js'
export { bindScrollLock, type ScrollLockOptions } from './scroll-lock.js'
export { trapFocus, focusableElements, type FocusTrapOptions } from './focus-trap.js'
export { makeDraggable } from './draggable.js'
export { acquireBehaviors, type BehaviorOptions } from './behaviors.js'
