export { createVueModal } from './manager.js'
export { useModal, useCurrentModal, onBeforeModalClose, useModalResolve, useModalSnapshot } from './composables.js'
export { ModalContainer } from './container.js'
export { ModalItem } from './item.js'
export { createModalRoute, installModalRouter } from './router.js'
export { MANAGER_KEY, HANDLE_KEY } from './keys.js'
export { injectStyles, STYLE_ID, MODAL_CSS } from './styles.js'
export type * from './types.js'
